name: MiTV SADA Streamer

on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'M3U8 Link yahan paste karein'
        required: true
        default: ''

jobs:
  mitv_live:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: 2. Start Live Stream (Unlimited Loop)
      run: |
        # -stream_loop -1 ka matlab hai video/link kabhi band nahi hoga
        ffmpeg -re -stream_loop -1 -user_agent "Mozilla/5.0" -i "${{ github.event.inputs.stream_url }}" \
        -c:v libx264 -preset ultrafast -b:v 2500k -maxrate 3000k -bufsize 6000k \
        -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 \
        -f flv "rtmp://a.rtmp.youtube.com/live2/4kpb-g391-9ym6-64er-4rag"
